###
GET http://localhost:3000/user-api/users

###
POST http://localhost:3000/user-api/users
Content-Type: application/json

{
    "id":201
    ,"name":"mahesh"
    ,"age":22
}

###
PUT http://localhost:3000/user-api/users/id
Content-Type: application/json

{
    "id":201
    ,"name":"mahesh karnati"
    ,"age":23
}
### Read a user by id
GET http://localhost:3000/user-api/users/201
###
DELETE http://localhost:3000/user-api/users/201
###
GET http://localhost:3000/user-api/users
###---------------------------------------------------------------------
###
GET http://localhost:3000/product-api/products

###
GET http://localhost:3000/product-api/products/10
###
GET http://localhost:3000/product-api/products-brand/cello
###
POST http://localhost:3000/product-api/products
Content-Type: application/json

{
    "id":10,
    "name":"pen",
    "price":10,
    "brand":"cello"
}
###
PUT http://localhost:3000/product-api/products/id
Content-Type: application/json

{
    "id":10,
    "name":"pen",
    "price":100,
    "brand":"cello"
}
###
DELETE http://localhost:3000/product-api/products/10
Content-Type: application/json

{
    "id":10,
    "name":"pen",
    "price":100,
    "brand":"cello"
}